skyflowapi/skyflow-python

skyflow/vault/_insert.py
This seems to fix the response parsing.
=> Fix batch insert response parsing

README.md, SECURITY.md
Signed-off-by: Shaik-Luqmaan <luqmaan.shaik@skyflow.com>
=> SDK-616- Add SECURITY.md and security email in readme file

README.md
Signed-off-by: Shaik-Luqmaan <luqmaan.shaik@skyflow.com>
=> SDK-773/ Update Generate bearer token method in README for Python SDK

samples/get_by_ids_sample.py, skyflow/_utils.py, skyflow/errors/_skyflow_errors.py, skyflow/vault/_client.py, skyflow/vault/_get_by_id.py, tests/vault/test_get_by_id.py
Uncovered lines will be covered in integration tests.
=> SK-260 get records by unique column values and updated get_by_id interface

skyflow/vault/_client.py, skyflow/vault/_config.py, skyflow/vault/_insert.py, skyflow/version.py, tests/vault/test_insert.py
- SK-1020 Test Driven Development for continue_on_error support in Insert Options
=> SK-1016 TDD continue_on_error support in Insert Options - Python SDK

CHANGELOG.md, README.md, samples/detokenize_with_continue_on_error_sample.py, samples/insert_with_continue_on_error_sample.py
- SK-1022 `README`, `CHANGELOG` and Samples for Continue On Error in Insert & Detokenize
- SK-1026 `README`, `CHANGELOG` and Samples for Continue On Error in Detokenize Method
=> SK-1022 README CHANGELOG and Samples for Continue On Error in Insert & Detokenize

CHANGELOG.md, README.md, samples/detokenize_with_continue_on_error_sample.py, samples/insert_with_continue_on_error_sample.py, skyflow/errors/_skyflow_errors.py, skyflow/vault/_client.py, skyflow/vault/_config.py, skyflow/vault/_detokenize.py, skyflow/vault/_insert.py, skyflow/version.py, tests/vault/test_detokenize.py, tests/vault/test_insert.py
- SK-1023 Support continue_on_error in Insert 
- SK-1027 Support continue_on_error in Detokenize
=> SK-1023/Release/23.9.1

CHANGELOG.md, README.md, samples/query_sample.py
- SK-975 Updated `README` and `CHANGELOG`
- SK-975 Added Sample for Query method
=> SK-907 Query Support in Python SDK

skyflow/errors/_skyflow_errors.py, skyflow/vault/_client.py, skyflow/vault/_config.py, skyflow/vault/_insert.py, tests/vault/test_insert.py
- SK-1036 Test Driven Development - BYOT strict mode in Insert.
=> SK-1019 BYOT strict mode in insert - Python SDK

skyflow/vault/_insert.py, tests/vault/test_insert.py
- `continueOnError` is true
- `continueOnError` is false and response is complete success
=> SK-1084 Add request_index in batch insert responses when

CHANGELOG.md, README.md
=> SK-1088 Update README and CHANGELOG

skyflow/errors/_skyflow_errors.py
SK-1036 Change Error message for BYOT related validation errors
=> SK-1036 Change Error message for BYOT related validation errors

.github/workflows/semgrep.yml, .semgreprules/customRule.yml
Implementing Semgrep for this repository
=> SC-3121:Create Semgrep

skyflow/utils/__init__.py, skyflow/utils/_utils.py, skyflow/vault/controller/_vault.py, tests/utils/test__utils.py, tests/vault/controller/test__vault.py
**Why**  
Column values were not encoded while retrieving records, leading to issues when special characters were present in the column values.
**Goal**  
Ensure that records can be retrieved even if column values contain special characters.
=> SK-1736: Added encoding for column values in get interface

setup.py
**Why**  
Some packages were missing in the requirements, which could cause issues when running the interfaces.
**Goal**  
Ensure the interfaces run smoothly without any package-related issues.
=> SK-1736: Update requirements.txt

.github/workflows/ci.yml, .github/workflows/main.yml
- Bump python version from 3.7 to 3.8
=> SK-1772: Update commit message pattern

README.md
This PR contains updated README content for SDK v2.
- The previous README for SDK v2 became outdated as we received feedback to improve it.
- The updated README will provide a clear and accurate representation of the v2 SDK’s improving developer understanding and usability.
=> SK-1894: Update README for Python SDK V2

.github/workflows/semgrep.yml
This workflow automatically runs Semgrep scans on pull requests to identify security vulnerabilities. All findings are displayed in the build log for review.
If any issues are detected, a comment is posted directly on the PR.
=> SC-5131:Update semgrep.yml

README.md, samples/detect_api/deidentify_file.py, samples/detect_api/deidentify_text.py, samples/detect_api/get_detect_run.py, samples/detect_api/reidentify_text.py
**Why**
- Lack of a README and samples for the newly added "detect public interfaces" feature.
**Outcome**
- Provision of comprehensive samples and a README to facilitate the execution of the "detect public interfaces" functionality.
=> SK-2068: Add samples and update README for detect public interfaces.

setup.py, skyflow/vault/_client.py, skyflow/version.py
- To make the retry as the latest patch fix for version 1.15.x
- This way the long term fix with request sessions will not affect the other users
=> SK-2313 Release/25.9.15
